import { PGlite } from '@electric-sql/pglite';import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role authenticated;create schema auth;
create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('test.jwt',true),''),'{}')::jsonb$$;
create function auth.uid() returns uuid language sql stable as $$select nullif(auth.jwt()->>'sub','')::uuid$$;
create function public.is_manager() returns boolean language sql stable as $$select coalesce(auth.jwt()->'app_metadata'->>'role'='manager',false)$$;
create table media_items(id uuid primary key default gen_random_uuid(),organization_id uuid,size_bytes bigint);
create table playlists(id uuid primary key default gen_random_uuid(),organization_id uuid,name text);
create table playlist_items(id uuid primary key default gen_random_uuid(),playlist_id uuid,media_id uuid);`);
const org='00000000-0000-0000-0000-000000000001',other='00000000-0000-0000-0000-000000000002',user='00000000-0000-0000-0000-000000000003';
await db.query('insert into media_items(organization_id,size_bytes) select $1,10 from generate_series(1,1001)',[org]);
const media=(await db.query('insert into media_items(organization_id,size_bytes) values($1,999999) returning id',[other])).rows[0].id;
const own=(await db.query('select id from media_items where organization_id=$1 limit 1',[org])).rows[0].id;
const list=(await db.query("insert into playlists(organization_id,name) values($1,'Opening') returning id",[org])).rows[0].id;
await db.query('insert into playlist_items(playlist_id,media_id) values($1,$2),($1,$2)',[list,own]);
const sql=readFileSync(new URL('../../supabase/operational-summary.sql',import.meta.url),'utf8');await db.exec(sql);await db.exec(sql);
const actor=async(role,organization=org)=>db.query("select set_config('test.jwt',$1,false)",[JSON.stringify({sub:user,app_metadata:{role,organization_id:organization}})]);
await assert.rejects(db.query('select screenflow_operational_summary($1)',[org]),/Niet ingelogd/);
await actor('customer_admin');
const result=(await db.query('select screenflow_operational_summary($1) data',[org])).rows[0].data;
assert.equal(result.media_count,1001);assert.equal(result.media_bytes,10010);assert.ok(result.server_time);
await assert.rejects(db.query('select screenflow_operational_summary($1)',[other]),/Geen toegang/);
await assert.rejects(db.query('select screenflow_operational_summary(null)'),/Geen toegang/);
await assert.rejects(db.query('select screenflow_media_dependencies($1)',[media]),/Geen toegang/);
const deps=(await db.query('select screenflow_media_dependencies($1) data',[own])).rows[0].data;assert.equal(deps.length,1);assert.equal(deps[0].uses,2);
await actor('manager');assert.ok((await db.query('select screenflow_operational_summary(null) data')).rows[0].data.server_time);
await db.close();console.log('PASS: SQL rerunnable, >1000 files counted, foreign/anonymous denied, dependencies counted and manager server clock.');
