import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role authenticated;create schema auth;
create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('test.jwt',true),''),'{}')::jsonb$$;
create function auth.uid() returns uuid language sql stable as $$select nullif(auth.jwt()->>'sub','')::uuid$$;
create function public.is_manager() returns boolean language sql stable as $$select coalesce(auth.jwt()->'app_metadata'->>'role'='manager',false)$$;
create table organizations(id uuid primary key);create table devices(id uuid primary key);
create table support_requests(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,created_by uuid not null,subject text,description text,priority text default 'normal',status text default 'new' check(status in ('new','in_progress','waiting_customer','resolved')),manager_note text,manager_viewed_at timestamptz,created_at timestamptz default now(),updated_at timestamptz default now());
create table support_request_messages(id uuid primary key default gen_random_uuid(),request_id uuid references support_requests,organization_id uuid,sender_id uuid,sender_role text,message text,manager_viewed_at timestamptz,customer_viewed_at timestamptz,created_at timestamptz default now());`);
const org='00000000-0000-0000-0000-000000000001',other='00000000-0000-0000-0000-000000000002',user='00000000-0000-0000-0000-000000000003';
await db.query('insert into organizations values($1),($2)',[org,other]);
await db.query("insert into support_requests(organization_id,created_by,subject) values($1,$2,'Legacy')",[org,user]);
const sql=readFileSync(new URL('../../supabase/ticket-archive.sql',import.meta.url),'utf8');
await db.exec(sql);await db.exec(sql);
const actor=async(role,organization=org)=>db.query("select set_config('test.jwt',$1,false)",[JSON.stringify({sub:user,app_metadata:{role,organization_id:organization}})]);
await actor('customer_admin');
const r=(await db.query("insert into support_requests(organization_id,created_by,subject,ticket_number,status) values($1,$2,'Test','spoof','resolved') returning *",[org,user])).rows[0];
assert.match(r.ticket_number,/^SFT-\d+$/);assert.equal(r.status,'new');assert.notEqual(r.ticket_number,'spoof');
await assert.rejects(db.query('select customer_confirm_support_request($1)',[r.id]),/nog niet/);
await actor('manager');
await assert.rejects(db.query("select manager_reply_to_request($1,'','resolved')",[r.id]),/Beschrijf/);
await db.query("select manager_reply_to_request($1,'HDMI kabel vervangen','resolved')",[r.id]);
assert.equal((await db.query('select archived_at from support_requests where id=$1',[r.id])).rows[0].archived_at,null);
await assert.rejects(db.query('select customer_confirm_support_request($1)',[r.id]),/niet gevonden/);
await actor('customer_admin',other);
await assert.rejects(db.query('select customer_confirm_support_request($1)',[r.id]),/niet gevonden/);
await actor('customer_admin');
await db.query('select customer_confirm_support_request($1)',[r.id]);
await db.query('select customer_confirm_support_request($1)',[r.id]);
assert.ok((await db.query('select archived_at from support_requests where id=$1',[r.id])).rows[0].archived_at);
await actor('manager');
await assert.rejects(db.query("select manager_reply_to_request($1,'Nog iets','in_progress')",[r.id]),/gearchiveerd/);
await assert.rejects(db.query("update support_requests set ticket_number='changed' where id=$1",[r.id]),/onveranderbaar/);
await assert.rejects(db.query("update support_requests set archived_at=null where id=$1",[r.id]),/gearchiveerd/);
await assert.rejects(db.query("insert into support_request_messages(request_id,organization_id,sender_id,sender_role,message) values($1,$2,$3,'customer','old app')",[r.id,org,user]),/gearchiveerd/);
await db.exec(sql);
assert.equal((await db.query('select count(distinct ticket_number)::int n from support_requests')).rows[0].n,2);
await db.close();console.log('PASS: migration rerun, unique immutable tickets, solution required, manager/foreign customer denied, own customer confirms, archive immutable.');
